import { Image } from "antd";
import classNames from "classnames";
import Head from "next/head";
import { FC, Fragment } from "react";
import Layout from "../components/Layout";
import { ScrollAnimateClass } from "../constant";
import styles from "../styles/doc.module.less";
const doc: FC = () => {
  return (
    <Fragment>
      <Head>
        <title>OnChain PLM 平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div style={{ height: "80px" }}></div>
        <div className={styles.topImg}>
          <div>产品文档</div>
        </div>
      </Layout>
    </Fragment>
  );
};

export default doc;
