import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.less";
import { Button } from "antd";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { getPosts } from "./api/hello";
import { FC } from "react";

// home -- first page
const AdvertiseBox: FC = (props) => {
  return (
    <div className={styles.advertise_container}>
      <div className={styles.advertise_box}>
        <div className={styles.advertise_box_title}>
          <span className={styles.advertise_box_title_1}>
            新一代超融合云原生技术
          </span>
          <br />
          <span className={styles.advertise_box_title_2}>
            产品全生命周期赋能平台
          </span>
        </div>
        <div className={styles.advertise_box_sub_title}>
          简化产品开发并在云中快速交付创新产品
        </div>
        <div className={styles.advertise_box_sub_title}>
          探索OnChain云原生产品生命周期管理(PLM)解决方案的优势
        </div>
        <div className={styles.advertise_box_sub_button_group}>
          <Button>申请试用</Button>
          <Button>视频介绍</Button>
        </div>
      </div>
    </div>
  );
};

export default function Home({ posts }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <AdvertiseBox></AdvertiseBox>
      </main>
      <Footer></Footer>
    </div>
  );
}

// export async function getStaticProps(context: any) {
//   const posts = await getPosts();
//   if (!posts) {
//     return {
//       notFound: true,
//     };
//   }

//   return {
//     props: { posts },
//   };
// }
