import classNames from "classnames";
import Head from "next/head";
import { FC, Fragment } from "react";
import Layout from "../components/Layout";
import { ScrollAnimateClass } from "../constant";
import styles from "../styles/Platform.module.less";

interface RenderContent {
  img?: string;
  content?: string;
  title?: string;
  contentKey: number;
}

const RenderContent: FC<RenderContent> = (props) => {
  const isOdd = props.contentKey % 2 === 0;
  return (
    <div
      className={styles.platform_container}
      style={{ background: isOdd ? "#fff" : "#f5f5f5" }}
    >
      <div
        className={classNames({
          [styles.platform_item]: true,
          [ScrollAnimateClass]: true,
          ["slideInLeft"]: isOdd,
          ["slideInRight"]: !isOdd,
        })}
        style={{ flexDirection: isOdd ? "row" : "row-reverse" }}
      >
        <div>
          <div className={styles.platform_item_title}>{props.title}</div>
          <div className={styles.platform_item_content}>{props.content}</div>
        </div>
        <div className={styles.platform_item_img}></div>
      </div>
    </div>
  );
};

export default () => {
  const data = [
    {
      img: "",
      content:
        "OnChainPLM基于云原生技术，来构建新一代工业软件技术底座“产品全生命周期赋能平台”，帮助企业高效管理其产品开发流程，并比竞争对手更快地将产品推向市场。您的整个产品数据在云端安全可靠，可从任何地方任何设备进行访问。",
      title: "云原生赋能平台",
    },
    {
      img: "",
      content:
        "OnChainPLM平台采用多租户和微服务架构构建。您的产品数据与爱他用户产品数据相互隔离、安全可靠，并且应用程序由于分布式和优化的系统资源高效运行。",
      title: "多租户体系架构",
    },
    {
      img: "",
      content:
        "我们的平台提供多层数据安全和访问控制。借助对象权限和精细权限模型，您可以更好地控制谁可以访问数据以及他们可以做什么。",
      title: "安全和访问控制",
    },
    {
      img: "",
      content:
        "通过OnChain企业社交功能，方便连接产品团队中的各个角色人员，增强他们之间的协作。团队可以共享关键信息，如文档、文件、图纸等以及上下文研发数据。",
      title: "多维度企业协同",
    },
    {
      img: "",
      content: "通过我们的移动应用程序，您的团队可以从任何地方访问产品数据。",
      title: "企业移动",
    },
    {
      img: "",
      content:
        "定制化应用程序开发，方便为您的产品团队提供更好的用户体验。OnChainPLM平台提供低代码应用程序开发，基于Serverless技术，无需编写大量代码即可构建自定义应用程序。",
      title: "低代码开发",
    },
    {
      img: "",
      content:
        "平台内置 OPEN API 可以在安全环境中创建和访问数据。这些API可以通过不同的编程语言轻松访问。",
      title: "系统开放能力",
    },
    {
      img: "",
      content:
        "基于云原生超融合技术的应用架构，PLM 相关业务最终交付物会完全遵循云原生应用交付件标准去交付客户应用体。分钟级时间完成支撑工业级的云原生应用部过程。",
      title: "应用分发与交付能力",
    },
  ];
  return (
    <Fragment>
      <Head>
        <title>OnChain PLM 平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <div style={{ height: "80px" }}></div>
          {data.map((item, index) => (
            <RenderContent
              key={index}
              {...item}
              contentKey={index}
            ></RenderContent>
          ))}
        </div>
      </Layout>
    </Fragment>
  );
};
