import Head from "next/head";
import { Fragment } from "react";
import Layout from "../components/Layout";

export default () => {
  return (
    <Fragment>
      <Head>
        <title>OnChain PLM 平台</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>123</div>
      </Layout>
    </Fragment>
  );
};
